[package]
name = "AccountMultisig"
edition = "2024.beta"
license = "MIT"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"

[dependencies.AccountProtocol]
local = "../../protocol"

[dependencies.AccountExtensions]
local = "../../extensions"

[addresses]
account_multisig = "0x05d1c7b7b4381fb78b70ccb7f7c0786a383b74a3149b53661d5c759f968edf54"
account_protocol = "0x4803761efb11498331d8e70c741602dbbe2ddc97f667174931ccc669fd4fb958"
account_extensions = "0xe59b21cc35bf31b7cbc3e3f309fa810e059e481322ecf96518a608a15503b6d2"
